version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm -f install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
