version: 0.2

phases:
 install:
    runtime-versions:
      nodejs: 12
   
    commands:
        # install npm
        - npm install
      
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"

