version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
   
    commands:
        # install npm
        - npm install
       
  build:
    commands:
        # run build script
        - npm run-script build
artifacts:
  files:
    - "**/*"

