version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
   
    commands:
        # install npm
        - npm  -f install
       
  build:
    commands:
        # run build script
        - npm run build
artifacts:
  files:
    - "**/*"

